### ISSUE TITLE
User Info Endpoint Handling Expects Key "user" in Response

### ISSUE THREAD

**Issue by Namesonic** [Schine/MW-OAuth2Client#3]
I'm curious why in the _userHandling function you are expecting the $response['user'][...] key instead of just $response[...]?

The OPENID spec shows a key=>value JSON response https://connect2id.com/products/server/docs/api/userinfo

At the userinfo endpoint of my SSO provider, it returns a plain JSON object with key=>value pairs that are not inside a "user" object.

Is there any way to specify the return key, if any, being used in the userinfo endpoint response?  Or will I have to approach the SSO provider to return user info inside the "user" key?

```
protected function _userHandling( $response ) {
		global $wgOAuth2Client, $wgAuth, $wgRequest;
		$username = $response['user'][$wgOAuth2Client['configuration']['username']];
		$email = $response['user'][$wgOAuth2Client['configuration']['email']];
```

**Comment by Adriien-M** [comment]
+1 
It doesn't make sense, it should get value directly from the object root...

**Comment by Excited-ccccly** [comment]
@Namesonic @Adriien-M Hi, I have created a [pull request](https://github.com/Schine/MW-OAuth2Client/pull/7) to support nested json path that will fix this issue.

**Comment by nischayn22** [comment]
If someone can test the pull request, I can merge it :)

**Comment by Excited-ccccly** [comment]
@nischayn22 Actually, I have applied the fix in my test environment and it works! lol

**Comment by bibiwan** [comment]
@nischayn22 Same here, it works.

**Comment by nischayn22** [comment]
I just merged this. Thanks for your work. If anyone has issues with the patch please feel free to submit another pull request.
